stand:
   debug: true
   environment: desenv
   secret: 123456
   servers:
       database_url: mysql+pymysql://root:lemon@localhost:33062/stand
       redis_url: redis://redis_server:6379
   services:
       tahiti:
           url: https://dev.lemonade.org.br/api/v1/tahiti
           auth_token: 123456
       stand:
           url: https://dev.lemonade.org.br/api/v1/stand
           auth_token: 123456