"""add new job types

Revision ID: 025b039de38c
Revises: 75a8a5ab74c4
Create Date: 2022-01-31 16:45:54.881853

"""
from alembic import op
import sqlalchemy as sa

from stand.migration_utils import (is_mysql, get_psql_enum_alter_commands,
        upgrade_actions, downgrade_actions, is_sqlite)

# revision identifiers, used by Alembic.
revision = '025b039de38c'
down_revision = '75a8a5ab74c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###a

    if is_mysql():
        op.execute("""
            ALTER TABLE job CHANGE `type` `type`
                ENUM('APP','BATCH','MODEL_BUILDER','NORMAL')
                CHARSET utf8 COLLATE utf8_general_ci NOT NULL;
            """)
    elif is_sqlite():
        pass # No enum support in sqlite
    else:
        values = ['APP','BATCH','MODEL_BUILDER','NORMAL']
        all_commands = [[get_psql_enum_alter_commands(['job'], ['type'],
            'JobTypeEnumType', values, 'NORMAL'), 
            None]]


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_mysql():
        op.execute("""
            ALTER TABLE job CHANGE `type` `type`
                ENUM('APP','BATCH', 'NORMAL')
                CHARSET utf8 COLLATE utf8_general_ci NOT NULL;
            """)
    elif is_sqlite():
        pass # No enum support in sqlite
    else:
        values = ['APP','BATCH','NORMAL']
        all_commands = [[get_psql_enum_alter_commands(['job'], ['type'],
            'JobTypeEnumType', values, 'NORMAL'), 
            None]]

