"""empty message

Revision ID: 03dbc173d79a
Revises: 306f880b11c3
Create Date: 2019-07-02 09:51:57.061080

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03dbc173d79a'
down_revision = '306f880b11c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_platform',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('platform_id', sa.Integer(), nullable=False),
                    sa.Column('cluster_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('job_step_log', 'message',
                    existing_type=mysql.LONGTEXT(),
                    nullable=False)

    op.execute("""
        ALTER TABLE cluster CHANGE `type` `type`
            ENUM('MESOS','YARN','SPARK_LOCAL','KUBERNETES')
            CHARSET utf8 COLLATE utf8_general_ci NOT NULL;
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_step_log', 'message',
                    existing_type=mysql.LONGTEXT(),
                    nullable=True)
    op.drop_table('cluster_platform')
    # ### end Alembic commands ###
