"""add deleted flag to pipeline run

Revision ID: 1099ab576c7e
Revises: 3342a49db58e
Create Date: 2026-05-26 09:27:51.378511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1099ab576c7e'
down_revision = '3342a49db58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_run', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('pipeline_run', sa.Column('tags', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_pipeline_run_tags'), 'pipeline_run', ['tags'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_run_tags'), table_name='pipeline_run')
    op.drop_column('pipeline_run', 'tags')
    op.drop_column('pipeline_run', 'deleted')
    # ### end Alembic commands ###
