"""empty message

Revision ID: 180411a1d1a0
Revises: caae322c390f
Create Date: 2017-03-02 13:58:43.262140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180411a1d1a0'
down_revision = 'caae322c390f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('status_text', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'status_text')
    ### end Alembic commands ###
