"""add trigger mode column

Revision ID: 3342a49db58e
Revises: f9c21926fb26
Create Date: 2025-05-08 10:07:43.170316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3342a49db58e'
down_revision = 'f9c21926fb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_step_run', sa.Column('trigger_mode', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_step_run', 'trigger_mode')
    # ### end Alembic commands ###
