"""empty message

Revision ID: 4684b898ed0f
Revises: 180411a1d1a0
Create Date: 2017-03-03 14:54:31.226646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4684b898ed0f'
down_revision = '180411a1d1a0'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('VISUALIZATION', 'HTML', 'TEXT', 'OTHER', 'MODEL', name='ResultTypeEnumType'), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_result')
    ### end Alembic commands ###
