"""Add column to PipelineStepRun

Revision ID: 4fe0790b8423
Revises: fcca200be4a0
Create Date: 2024-07-03 22:58:22.589267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe0790b8423'
down_revision = 'fcca200be4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_step_run', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_step_run', 'order')
    # ### end Alembic commands ###
