"""Cluster flavor

Revision ID: 58c18ed26615
Revises: 03dbc173d79a
Create Date: 2019-07-10 09:56:35.764441

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58c18ed26615'
down_revision = '03dbc173d79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_flavor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=False),
                    sa.Column('enabled', sa.String(length=200), nullable=False),
                    sa.Column('parameters', mysql.LONGTEXT(), nullable=False),
                    sa.Column('cluster_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    op.execute("ALTER TABLE `stand`.`job_result` CHANGE `type` `type` "
               "ENUM('VISUALIZATION','HTML','TEXT','OTHER','MODEL','METRIC')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_flavor')
    # ### end Alembic commands ###
