"""Add field to pipeline step run

Revision ID: 7455e0294bbf
Revises: be3ad0bbc338
Create Date: 2024-07-13 13:07:54.343079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7455e0294bbf'
down_revision = 'be3ad0bbc338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_step_run', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_step_run', 'name')
    # ### end Alembic commands ###
