"""Add column operation_id to job_result

Revision ID: 8eaa98685eb3
Revises: 4684b898ed0f
Create Date: 2017-03-03 16:21:48.183888

"""
from alembic import op
import sqlalchemy as sa
from stand.migration_utils import is_sqlite


# revision identifiers, used by Alembic.
revision = '8eaa98685eb3'
down_revision = '4684b898ed0f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('job_result') as batch_op:
            batch_op.add_column(sa.Column('operation_id', sa.Integer(), nullable=False, 
                server_default='0'))
    else:
        op.add_column('job_result', sa.Column('operation_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    if is_sqlite():
        with op.batch_alter_table('job_result') as batch_op:
            batch_op.drop_column('operation_id')
    else:
        op.drop_column('job_result', 'operation_id')
    ### end Alembic commands ###
