"""empty message

Revision ID: 8eaa98685eb3
Revises: 4684b898ed0f
Create Date: 2017-03-03 16:21:48.183888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eaa98685eb3'
down_revision = '4684b898ed0f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_result', sa.Column('operation_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_result', 'operation_id')
    ### end Alembic commands ###
