"""Add fields to job related to pipeline run

Revision ID: 9495a3b32dc2
Revises: 7455e0294bbf
Create Date: 2024-08-01 11:10:44.154504

"""
from alembic import op
import sqlalchemy as sa
from stand.migration_utils import is_mysql

# revision identifiers, used by Alembic.
revision = '9495a3b32dc2'
down_revision = '7455e0294bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('description', sa.String(length=400), nullable=True))
    op.add_column('job', sa.Column('pipeline_run_id', sa.Integer(), nullable=True))
    if is_mysql():
        op.alter_column('job', 'status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   existing_nullable=False)
        op.create_foreign_key('fk_job_pipeline_run_id', 'job', 'pipeline_run', ['pipeline_run_id'], ['id'])
        op.create_foreign_key('fk_job_pipeline_step_run_id', 'job', 'pipeline_step_run', ['pipeline_step_run_id'], ['id'])
        op.alter_column('job_step', 'status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   existing_nullable=False)
        op.alter_column('job_step_log', 'status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'WAITING'"))
        op.alter_column('pipeline_run', 'status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   existing_nullable=False)
        op.alter_column('pipeline_run', 'final_status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   existing_nullable=True)
        op.alter_column('pipeline_step_run', 'status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   existing_nullable=False)
        op.alter_column('pipeline_step_run', 'final_status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_mysql():
        op.alter_column('pipeline_step_run', 'final_status',
                   existing_type=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=True)
        op.alter_column('pipeline_step_run', 'status',
                   existing_type=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=False)
        op.alter_column('pipeline_run', 'final_status',
                   existing_type=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=True)
        op.alter_column('pipeline_run', 'status',
                   existing_type=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=False)
        op.alter_column('job_step_log', 'status',
                   existing_type=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=False,
                   existing_server_default=sa.text("'WAITING'"))
        op.alter_column('job_step', 'status',
                   existing_type=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=False)
        op.drop_constraint('fk_job_pipeline_step_run_id', 'job', type_='foreignkey')
        op.drop_constraint('fk_job_pipeline_run_id', 'job', type_='foreignkey')
        op.alter_column('job', 'status',
                   existing_type=sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', 'WAITING_INTERVENTION', name='StatusExecutionEnumType'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=False)
        op.alter_column('job', 'type',
                   existing_type=sa.Enum('APP', 'BATCH', 'MODEL_BUILDER', 'NORMAL', name='JobTypeEnumType'),
                   type_=sa.VARCHAR(length=6),
                   existing_nullable=False,
                   existing_server_default=sa.text("'NORMAL'"))
    op.drop_column('job', 'pipeline_run_id')
    op.drop_column('job', 'description')
    # ### end Alembic commands ###
