"""Add column type to job_step_log

Revision ID: 989ff41dc23a
Revises: 2f2e97f51d5f
Create Date: 2017-08-01 16:14:45.386487

"""
from alembic import op
import sqlalchemy as sa
from stand.migration_utils import is_sqlite


# revision identifiers, used by Alembic.
revision = '989ff41dc23a'
down_revision = '2f2e97f51d5f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('job_step_log') as batch_op:
            batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False, 
            server_default=''))
    else:
        op.add_column('job_step_log', sa.Column(
            'type', sa.String(length=50), nullable=False))

    op.execute("UPDATE job_step_log SET type = 'TEXT'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('job_step_log') as batch_op:
            batch_op.drop_column('type')
    else:
        op.drop_column('job_step_log', 'type')
    ### end Alembic commands ###
