"""empty message

Revision ID: 989ff41dc23a
Revises: 2f2e97f51d5f
Create Date: 2017-08-01 16:14:45.386487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989ff41dc23a'
down_revision = '2f2e97f51d5f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_step_log', sa.Column(
        'type', sa.String(length=50), nullable=False))
    op.execute("UPDATE job_step_log SET type = 'TEXT'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_step_log', 'type')
    ### end Alembic commands ###
