"""Add column pipeline_name

Revision ID: be3ad0bbc338
Revises: 4fe0790b8423
Create Date: 2024-07-12 10:17:34.043475

"""
from alembic import op
import sqlalchemy as sa

from stand.migration_utils import is_sqlite
# revision identifiers, used by Alembic.
revision = 'be3ad0bbc338'
down_revision = '4fe0790b8423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    if is_sqlite():
        op.add_column('pipeline_run', sa.Column('pipeline_name', sa.String(length=200), nullable=True, 
            ))
        op.add_column('pipeline_run', sa.Column('updated', sa.DateTime(), nullable=True))
    else:
        op.add_column('pipeline_run', sa.Column('pipeline_name', sa.String(length=200), nullable=False, 
            server_default=''))
        op.add_column('pipeline_run', sa.Column('updated', sa.DateTime(), nullable=False, 
            server_default=sa.func.current_timestamp()))
    op.create_index(op.f('ix_pipeline_run_updated'), 'pipeline_run', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_run', 'pipeline_name')
    op.drop_index(op.f('ix_pipeline_run_updated'), table_name='pipeline_run')
    op.drop_column('pipeline_run', 'updated')
