"""empty message

Revision ID: d1e8bb87d422
Revises: 58c18ed26615
Create Date: 2019-10-17 09:48:21.019329

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1e8bb87d422'
down_revision = '58c18ed26615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('auth_token', sa.String(length=1000),
                                       nullable=False))
    op.alter_column('job_result', 'type',
                    existing_type=mysql.ENUM('VISUALIZATION', 'HTML', 'TEXT',
                                             'OTHER', 'MODEL', 'METRIC'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_result', 'type',
                    existing_type=mysql.ENUM('VISUALIZATION', 'HTML', 'TEXT',
                                             'OTHER', 'MODEL', 'METRIC'),
                    nullable=True)
    op.drop_column('cluster', 'auth_token')
    # ### end Alembic commands ###
