"""add context to pipeline run

Revision ID: f9c21926fb26
Revises: fa2e64620ede
Create Date: 2025-04-03 18:17:02.193870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9c21926fb26'
down_revision = 'fa2e64620ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run_context_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=4000), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], name='fk_pipeline_run_context_data_pipeline_run_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_run_context_data_pipeline_run_id'), 'pipeline_run_context_data', ['pipeline_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_pipeline_run_context_data_pipeline_run_id'), table_name='pipeline_run_context_data')
    op.drop_table('pipeline_run_context_data')
    # ### end Alembic commands ###
