"""Add field run_creation_method

Revision ID: fa2e64620ede
Revises: 9495a3b32dc2
Create Date: 2024-12-04 11:01:44.920475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa2e64620ede'
down_revision = '9495a3b32dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_run', sa.Column('run_creation_method', sa.String(length=50), nullable=False, 
        server_default='scheduler'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_run', 'run_creation_method')
    # ### end Alembic commands ###
