"""add new tables for pipeline

Revision ID: fcca200be4a0
Revises: 025b039de38c
Create Date: 2024-06-20 10:14:27.158188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcca200be4a0'
down_revision = '025b039de38c'
branch_labels = None
depends_on = None


def upgrade():
    return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('finish', sa.DateTime(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('last_executed_step', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', name='StatusExecutionEnumType'), nullable=False),
    sa.Column('final_status', sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', name='StatusExecutionEnumType'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_run_finish'), 'pipeline_run', ['finish'], unique=False)
    op.create_index(op.f('ix_pipeline_run_pipeline_id'), 'pipeline_run', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_run_start'), 'pipeline_run', ['start'], unique=False)
    op.create_table('pipeline_step_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', name='StatusExecutionEnumType'), nullable=False),
    sa.Column('final_status', sa.Enum('COMPLETED', 'ERROR', 'INTERRUPTED', 'PENDING', 'RUNNING', 'WAITING', 'CANCELED', name='StatusExecutionEnumType'), nullable=True),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], name='fk_pipeline_step_run_pipeline_run_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_step_run_pipeline_run_id'), 'pipeline_step_run', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_step_run_updated'), 'pipeline_step_run', ['updated'], unique=False)
    op.create_index(op.f('ix_pipeline_step_run_workflow_id'), 'pipeline_step_run', ['workflow_id'], unique=False)
    op.create_table('pipeline_step_run_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=200), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('pipeline_step_run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_step_run_id'], ['pipeline_step_run.id'], name='fk_pipeline_step_run_log_pipeline_step_run_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_step_run_log_pipeline_step_run_id'), 'pipeline_step_run_log', ['pipeline_step_run_id'], unique=False)
    op.create_index(op.f('ix_cluster_access_cluster_id'), 'cluster_access', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_configuration_cluster_id'), 'cluster_configuration', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_flavor_cluster_id'), 'cluster_flavor', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_platform_cluster_id'), 'cluster_platform', ['cluster_id'], unique=False)
    op.add_column('job', sa.Column('trigger_type', sa.Enum('MANUAL', 'TIME_SCHEDULE', 'MESSAGE', 'API', 'WATCH', 'OTHER', name='TriggerTypeEnumType'), nullable=True))
    op.add_column('job', sa.Column('pipeline_step_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_job_cluster_id'), 'job', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_job_pipeline_step_run_id'), 'job', ['pipeline_step_run_id'], unique=False)
    op.create_foreign_key('fk_job_pipeline_step_run_id', 'job', 'pipeline_step_run', ['pipeline_step_run_id'], ['id'])
    op.create_index(op.f('ix_job_result_job_id'), 'job_result', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_step_job_id'), 'job_step', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_step_log_step_id'), 'job_step_log', ['step_id'], unique=False)
    op.create_index(op.f('ix_room_participant_room_id'), 'room_participant', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'pipeline_step_run_id')
    op.drop_column('job', 'trigger_type')
    op.drop_table('pipeline_step_run_log')
    op.drop_table('pipeline_step_run')
    op.drop_table('pipeline_run')
    # ### end Alembic commands ###
